import './globals.css';
import 'leaflet/dist/leaflet.css';
import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import Navbar from '../app/components/Navbar';
import ScrollToTop from '../app/components/ScrollToTop';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Taxi App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-white transition-colors">
            <Navbar />
            {children}
            <ScrollToTop />
        </div>
        </body>
        </html>
    );
}
